apiVersion: v2
name: kumquat-mysql-cluster
description: Repository-managed MySQL InnoDB Cluster deployment for Kumquat.
type: application
version: 0.1.0
dependencies:
  - name: mysql-innodbcluster
    version: 2.2.7
    repository: https://mysql.github.io/mysql-operator/
