# Generated by Django 5.2 on 2025-10-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0005_scraper_timeout_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
