# Generated by Django 5.2 on 2025-10-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0006_jobposting_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualScriptRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
