# Generated by Django 5.2 on 2025-10-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0007_manualscriptrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
