# Generated by Django 4.2.25 on 2025-10-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0008_jobposting_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='normalized_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
