apiVersion: v1
kind: Service
metadata:
  name: {{ include "kumquat-elasticsearch.fullname" . }}
  labels:
    {{- include "kumquat-elasticsearch.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kumquat-elasticsearch.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
