apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kumquat-elasticsearch.fullname" . }}
  labels:
    {{- include "kumquat-elasticsearch.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "kumquat-elasticsearch.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "kumquat-elasticsearch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kumquat-elasticsearch.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: elasticsearch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: cluster.name
              value: {{ .Values.esConfig.clusterName | quote }}
            - name: node.name
              value: {{ .Values.esConfig.nodeName | quote }}
            - name: xpack.security.enabled
              value: {{ ternary "true" "false" .Values.esConfig.securityEnabled | quote }}
            - name: ES_JAVA_OPTS
              value: {{ .Values.esConfig.javaOpts | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /_cluster/health?wait_for_status=yellow&timeout=1s
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
