# Copyright (c) 2026 Benjamin Levin. All Rights Reserved.
# Unauthorized use or distribution is strictly prohibited.
apiVersion: v2
name: kumquat-mysql-operator
description: Repository-managed MySQL Operator install for Kumquat.
type: application
version: 0.1.0
dependencies:
  - name: mysql-operator
    version: 2.2.7
    repository: https://mysql.github.io/mysql-operator/
