# Copyright (c) 2026 Benjamin Levin. All Rights Reserved.
# Unauthorized use or distribution is strictly prohibited.
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views.generic import RedirectView

from .sitemaps import sitemaps
from .views import (
    admin_containers_page_view,
    companies_api_view,
    cli_search_view,
    companies_page_view,
    company_detail_page_view,
    companies_admin_page_view,
    admin_dashboard_view,
    admin_dashboard_page_view,
    admin_node_delete_container_view,
    admin_node_delete_deployment_view,
    admin_node_launcher_auth_view,
    admin_node_launch_view,
    admin_node_logs_view,
    admin_node_proxy_view,
    admin_node_restart_view,
    admin_node_stop_view,
    admin_runtime_container_delete_view,
    admin_runtime_container_restart_view,
    admin_vonage_sms_view,
    admin_vonage_sms_page_view,
    auth_logout_view,
    early_access_signup_view,
    explorer_address_page_view,
    explorer_block_page_view,
    explorer_home_page_view,
    explorer_transaction_page_view,
    google_oauth_exchange_view,
    google_oauth_callback_view,
    google_oauth_start_view,
    healthz_view,
    home_page_view,
    jobs_api_view,
    jobs_api_docs_page_view,
    jobs_page_view,
    job_detail_page_view,
    jobs_admin_page_view,
    messages_view,
    privacy_policy_page_view,
    robots_txt_view,
    search_crawl_enqueue_view,
    sign_in_page_view,
    terms_of_service_page_view,
    vonage_sms_callback_view,
    wallet_generate_view,
    wallet_regenerate_view,
)

urlpatterns = [
    path("", home_page_view, name="home"),
    path("privacy-policy", privacy_policy_page_view, name="privacy-policy"),
    path("terms", terms_of_service_page_view, name="terms-of-service"),
    path("jobs", jobs_page_view, name="jobs"),
    path("jobs/<slug:slug>", job_detail_page_view, name="job-detail"),
    path("companies", companies_page_view, name="companies"),
    path("companies/<slug:slug>", company_detail_page_view, name="company-detail"),
    path("api/jobs", jobs_api_view, name="jobs-api"),
    path("api/companies", companies_api_view, name="companies-api"),
    path("api/search/cli", cli_search_view, name="cli-search"),
    path("api/jobs/docs", jobs_api_docs_page_view, name="jobs-api-docs"),
    path("manage/jobs", jobs_admin_page_view, name="manage-jobs"),
    path("manage/companies", companies_admin_page_view, name="manage-companies"),
    path("", include("scrapers.urls")),
    path("explorer", explorer_home_page_view, name="explorer"),
    path("explorer/blocks/<str:identifier>", explorer_block_page_view, name="explorer-block"),
    path("explorer/transactions/<str:tx_hash>", explorer_transaction_page_view, name="explorer-transaction"),
    path("explorer/addresses/<str:address>", explorer_address_page_view, name="explorer-address"),
    path("search/crawl", search_crawl_enqueue_view, name="search-crawl"),
    path("robots.txt", robots_txt_view, name="robots-txt"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path("auth/sign-in", sign_in_page_view, name="sign-in"),
    path("auth/google/start", google_oauth_start_view, name="auth-google-start"),
    path("auth/google/callback", google_oauth_callback_view, name="auth-google-callback"),
    path("auth/google/exchange", google_oauth_exchange_view, name="auth-google-exchange"),
    path("auth/logout", auth_logout_view, name="auth-logout"),
    path("dashboard", admin_dashboard_page_view, name="dashboard"),
    path("dashboard/data", admin_dashboard_view, name="dashboard-data"),
    path("containers", admin_containers_page_view, name="containers"),
    path("nodes/launcher-auth", admin_node_launcher_auth_view, name="node-launcher-auth"),
    path("nodes/launch", admin_node_launch_view, name="node-launch"),
    path("nodes/<int:node_id>/logs", admin_node_logs_view, name="node-logs"),
    path("nodes/<int:node_id>/restart", admin_node_restart_view, name="node-restart"),
    path("nodes/<int:node_id>/stop", admin_node_stop_view, name="node-stop"),
    path("nodes/<int:node_id>/delete-container", admin_node_delete_container_view, name="node-delete-container"),
    path("nodes/<int:node_id>/delete-deployment", admin_node_delete_deployment_view, name="node-delete-deployment"),
    path("containers/runtime/<str:container_id>/restart", admin_runtime_container_restart_view, name="runtime-container-restart"),
    path("containers/runtime/<str:container_id>/delete", admin_runtime_container_delete_view, name="runtime-container-delete"),
    re_path(r"^nodes/(?P<node_id>\d+)/proxy(?:/(?P<subpath>.*))?$", admin_node_proxy_view, name="node-proxy"),
    path("sms", admin_vonage_sms_page_view, name="sms"),
    path("sms/data", admin_vonage_sms_view, name="sms-data"),
    path("early-access", early_access_signup_view, name="early-access"),
    path("healthz", healthz_view, name="healthz"),
    path("messages", messages_view, name="messages"),
    path("wallets/generate", wallet_generate_view, name="wallet-generate"),
    path("wallets/regenerate", wallet_regenerate_view, name="wallet-regenerate"),
    path("webhooks/vonage/sms", vonage_sms_callback_view, name="vonage-sms-callback"),
    path("admin/dashboard", RedirectView.as_view(url="/dashboard", permanent=False)),
    path("admin/vonage/sms", RedirectView.as_view(url="/sms", permanent=False)),
    path("api/auth/logout", RedirectView.as_view(url="/auth/logout", permanent=False)),
    path("api/admin/dashboard", RedirectView.as_view(url="/dashboard/data", permanent=False)),
    path("api/admin/vonage/sms", RedirectView.as_view(url="/sms/data", permanent=False)),
    path("api/admin/nodes/launch", RedirectView.as_view(url="/nodes/launch", permanent=False)),
]
