# Copyright (c) 2026 Benjamin Levin. All Rights Reserved.
# Unauthorized use or distribution is strictly prohibited.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kumquat-backend.fullname" . }}-ingress
  labels:
    {{- include "kumquat-backend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kumquat-backend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - ingress-nginx
